title: ReportBreach
modelClass: MaheshKS\ReportDataBreach\Models\DataBranch
list: $/maheshks/reportdatabreach/models/databranch/columns.yaml
recordUrl: 'maheshks/reportdatabreach/reportbreach/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
